authorName: zdy

spring:
  datasource:
    url: jdbc:mysql://rm-wz9794vc2ah3g166vio.mysql.rds.aliyuncs.com/authentication_center?useUnicode=true&characterEncoding=utf8
    username: root
    password: Ww4247794!
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: ".html"
    check-template-location: true
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    mode: html

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
mapper:
  mappers: cn.pubud.pugenerator.mapper.GeneratorMapper








